export const CancelOptionsDriver = {
  EXCEED_PASSENGER: 'EXCESO DE PASAJEROS',
  FAKE_TRIP: 'PEDIDO FALSO',
  I_REFUSE: 'ME REHÚSO A REALIZAR EL VIAJE',
  OTHER: 'OTRO',
};

export const CancelOptionsPassenger = {
  DIFFERENT_DRIVER: 'ES UN CONDUCTOR(A) DIFERENTE',
  DIFFERENT_CAR: 'ES UN CARRO DIFERENTE',
  OTHER: 'OTRO',
};
