export default {
  CHECKING: 'CHECKING',
  OFFERING: 'OFFERING',
  DRIVER_ACCEPTED: 'DRIVER_ACCEPTED',
  PASSENGER_ACCEPTED: 'PASSENGER_ACCEPTED',
  PASSENGER_DECLINE: 'PASSENGER_DECLINE',
  PASSENGER_CANCELED: 'PASSENGER_CANCELED',
  PASSENGER_ARRIVED: 'PASSENGER_ARRIVED',
  DRIVER_CANCELED: 'DRIVER_CANCELED',
  DRIVER_ARRIVED: 'DRIVER_ARRIVED',
  RIDE_CANCELED: 'RIDE_CANCELED',
  RIDE_STARTED: 'RIDE_STARTED',
  RIDE_FINISHED: 'RIDE_FINISHED',
};
